// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_caixa_igreja.Models;

#nullable disable

namespace api_caixa_igreja.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.Cargos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cargos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Pessoa com ficha de membro frequente aos cultos",
                            Nome = "Membro"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Pessoa Membra com responsabilidades na obra",
                            Nome = "Obreiro"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Pessoa auxiliadora do ministerio diaconal",
                            Nome = "Diacono"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Pessoa Obreita integrante do ministerio de louvor",
                            Nome = "Levita"
                        });
                });

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.Dizimos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdMembroDizimista")
                        .HasColumnType("int");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("IdMembroDizimista");

                    b.ToTable("Dizimos");
                });

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.Membros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataBatismo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.ToTable("Membros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargoId = 1,
                            DataBatismo = new DateTime(2010, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1995, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Rodolfo Jesus Silva"
                        },
                        new
                        {
                            Id = 2,
                            CargoId = 2,
                            DataBatismo = new DateTime(2008, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1993, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Kelly Cristina Martins"
                        },
                        new
                        {
                            Id = 3,
                            CargoId = 3,
                            DataBatismo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(2006, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Gustavo de Jesus Silva"
                        },
                        new
                        {
                            Id = 4,
                            CargoId = 4,
                            DataBatismo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(2000, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Casy Martins da Silva"
                        },
                        new
                        {
                            Id = 5,
                            CargoId = 4,
                            DataBatismo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1974, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "André Martinele Alves"
                        });
                });

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.Ofertas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdMembroMinistrante")
                        .HasColumnType("int");

                    b.Property<int>("IdMembroOfertante")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoCulto")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoOferta")
                        .HasColumnType("int");

                    b.Property<int?>("MembroOfertanteId")
                        .HasColumnType("int");

                    b.Property<int>("QtdAdultos")
                        .HasColumnType("int");

                    b.Property<int>("QtdCriancas")
                        .HasColumnType("int");

                    b.Property<double>("totalOferta")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("IdMembroMinistrante");

                    b.HasIndex("IdTipoCulto");

                    b.HasIndex("IdTipoOferta");

                    b.HasIndex("MembroOfertanteId");

                    b.ToTable("Ofertas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dia = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdMembroMinistrante = 1,
                            IdMembroOfertante = 0,
                            IdTipoCulto = 1,
                            IdTipoOferta = 1,
                            QtdAdultos = 26,
                            QtdCriancas = 5,
                            totalOferta = 550.25
                        });
                });

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.Primicias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdMembro")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoOferta")
                        .HasColumnType("int");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("IdMembro");

                    b.HasIndex("IdTipoOferta");

                    b.ToTable("Primicias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dia = new DateTime(2022, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdMembro = 1,
                            IdTipoOferta = 1,
                            Periodo = "07/2021",
                            Valor = 400.64999999999998
                        },
                        new
                        {
                            Id = 2,
                            Dia = new DateTime(2022, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdMembro = 2,
                            IdTipoOferta = 2,
                            Periodo = "06/2021",
                            Valor = 150.80000000000001
                        });
                });

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.TipoCulto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TipoCulto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Último domingo de cada mês. Ceia do Senhor para batizados nas águas.",
                            Nome = "Santa Ceia"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "No 4º domingo do mês quando há 5 domingos no mês.",
                            Nome = "Centésima ovelha"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "3º Domingo do mês. Ofertas destinadas para missão não ficam no caixa da igreja",
                            Nome = "Missões"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "2º Domingo. Geralmente nesse dia são devolvidos Dizimos e primicias",
                            Nome = "Properidade"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "1º Domingo do mês. Culto para batismo e renovo do espirito santo",
                            Nome = "Poder"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Todos os dias de semana. Seg a Sex",
                            Nome = "Graça"
                        });
                });

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.TipoOfertas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TipoOferta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Dinheiro em especie no culto.",
                            Nome = "Cédulas C."
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Dinheiro em especia fora do culto",
                            Nome = "Cédulas F."
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Transferencia de conta. (TED, DOC, PIX)",
                            Nome = "Transferência"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Cheques fora do culto",
                            Nome = "Cheques"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Feito com cartão crédito/debito",
                            Nome = "Cartão"
                        });
                });

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.Dizimos", b =>
                {
                    b.HasOne("api_caixa_igreja.Models.Entities.Membros", "MembroDizimista")
                        .WithMany("DizimosDevolvidos")
                        .HasForeignKey("IdMembroDizimista")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MembroDizimista");
                });

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.Membros", b =>
                {
                    b.HasOne("api_caixa_igreja.Models.Entities.Cargos", "Cargo")
                        .WithMany("Membros")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.Ofertas", b =>
                {
                    b.HasOne("api_caixa_igreja.Models.Entities.Membros", "MembroMinistrante")
                        .WithMany("OfertasMinistradas")
                        .HasForeignKey("IdMembroMinistrante")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api_caixa_igreja.Models.Entities.TipoCulto", "TipoCulto")
                        .WithMany("OfertasAlcadas")
                        .HasForeignKey("IdTipoCulto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api_caixa_igreja.Models.Entities.TipoOfertas", "TipoOferta")
                        .WithMany("OfertasAlcadas")
                        .HasForeignKey("IdTipoOferta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api_caixa_igreja.Models.Entities.Membros", "MembroOfertante")
                        .WithMany("OfertasRealizadas")
                        .HasForeignKey("MembroOfertanteId");

                    b.Navigation("MembroMinistrante");

                    b.Navigation("MembroOfertante");

                    b.Navigation("TipoCulto");

                    b.Navigation("TipoOferta");
                });

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.Primicias", b =>
                {
                    b.HasOne("api_caixa_igreja.Models.Entities.Membros", "Membro")
                        .WithMany("PrimiciasOfertadas")
                        .HasForeignKey("IdMembro")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api_caixa_igreja.Models.Entities.TipoOfertas", "TipoOferta")
                        .WithMany("PrimiciasOfertadas")
                        .HasForeignKey("IdTipoOferta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Membro");

                    b.Navigation("TipoOferta");
                });

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.Cargos", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.Membros", b =>
                {
                    b.Navigation("DizimosDevolvidos");

                    b.Navigation("OfertasMinistradas");

                    b.Navigation("OfertasRealizadas");

                    b.Navigation("PrimiciasOfertadas");
                });

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.TipoCulto", b =>
                {
                    b.Navigation("OfertasAlcadas");
                });

            modelBuilder.Entity("api_caixa_igreja.Models.Entities.TipoOfertas", b =>
                {
                    b.Navigation("OfertasAlcadas");

                    b.Navigation("PrimiciasOfertadas");
                });
#pragma warning restore 612, 618
        }
    }
}
